include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    prefer_relative_imports: true
    public_member_api_docs: false
    type_annotate_public_apis: false
    lines_longer_than_80_chars: false